# Generated by Django 3.0.1 on 2020-01-05 09:58

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='password',
            field=models.CharField(default=exchange.models.rand_string, max_length=10),
        ),
    ]
