# Generated by Django 3.0.1 on 2020-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='time_spent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
