# Generated by Django 3.0.1 on 2020-01-13 17:00

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_sketch_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='review_password',
            field=models.CharField(default=exchange.models.rand_string, max_length=10),
        ),
        migrations.AddField(
            model_name='sketch',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sketches', related_query_name='sketches', to='exchange.Exchange'),
        ),
    ]
