# Generated by Django 3.0.1 on 2020-01-15 20:58

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_assignment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='image',
            field=models.FileField(upload_to=exchange.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
