# Generated by Django 3.0.1 on 2020-01-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20200115_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='can_post_to_reddit',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1)], null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='excitement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
