# Generated by Django 3.0.1 on 2020-01-23 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20200121_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='posted_to_reddit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moniker', models.CharField(max_length=255)),
                ('style', models.CharField(blank=True, choices=[('handstyle', 'handstyle'), ('wildstyle', 'wildstyle'), ('throwie', 'throwie'), ('keyboard', 'keyboard'), ('piece', 'piece')], max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=1200, null=True)),
                ('do_double', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='recipient_signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favors', related_query_name='favor', to='exchange.Signup'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user_signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', related_query_name='assignment', to='exchange.Signup'),
        ),
    ]
