# Generated by Django 3.0.1 on 2020-01-23 07:54

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20200123_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketch',
            name='image',
            field=models.ImageField(upload_to=exchange.models.upload_to),
        ),
    ]
