# Generated by Django 3.0.1 on 2020-01-30 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20200123_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signups', related_query_name='signups', to='exchange.Exchange'),
            preserve_default=False,
        ),
    ]
