# Generated by Django 3.0.1 on 2020-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20200130_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='time_spent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
