# Generated by Django 3.0.1 on 2020-02-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_assignment_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='moniker',
        ),
    ]
