# Generated by Django 3.0.1 on 2020-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_remove_assignment_moniker'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
