# Generated by Django 3.0.1 on 2020-03-05 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_exchange_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='rematch_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='results_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='sign_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sketches', to=settings.AUTH_USER_MODEL),
        ),
    ]
